POST http://localhost:2055/houses
Content-Type: application/json

{
  "code": "GNK_001",
  "name": "Beautiful house in the city",
  "status": "SOLD",
  "city": "Genk",
  "price": 250000
}

###
POST http://localhost:2055/houses
Content-Type: application/json

{
  "code": "HAS_003",
  "name": "Cozy bungalow",
  "status": "FOR_SALE",
  "city": "Hasselt",
  "price": 180000
}

###
GET http://localhost:2055/houses
